"""Contracts for source-aware code ingestion."""

from .contracts import (
    CodeFile,
    CodeIngestionError,
    CodeParseError,
    CodeParseResult,
    CodeSource,
    CodeSourceKind,
    CodeSymbol,
    CodeSymbolType,
    Language,
    LanguageParser,
    ParseError,
    SourceValidationError,
    UnsupportedLanguageError,
)
from .discovery import (
    DEFAULT_MAX_FILE_SIZE,
    EXCLUDED_DIRECTORIES,
    CodeDiscovery,
    DiscoveryIssue,
    DiscoveryReason,
    DiscoveryResult,
    DiscoveryStatistics,
    classify_language,
)

__all__ = [
    "DEFAULT_MAX_FILE_SIZE",
    "EXCLUDED_DIRECTORIES",
    "CodeDiscovery",
    "CodeFile",
    "CodeIngestionError",
    "CodeParseError",
    "CodeParseResult",
    "CodeSource",
    "CodeSourceKind",
    "CodeSymbol",
    "CodeSymbolType",
    "DiscoveryIssue",
    "DiscoveryReason",
    "DiscoveryResult",
    "DiscoveryStatistics",
    "Language",
    "LanguageParser",
    "ParseError",
    "SourceValidationError",
    "UnsupportedLanguageError",
    "classify_language",
]
